Repository bitfireAT/davx5-ose, pull requests merged in 2023-10, with the labels that each got.

#444 BatteryOptimizationIntroFragment: use contract instead of onActivityResult
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsFragment.kt
Labels: enhancement

#450 PermissionsIntroFragment: take jtx Board and tasks.org permissions into account
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/PermissionsIntroFragment.kt
Labels: bug

#452 Make all IntroFragments appear at first start
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroFragmentFactory.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/OpenSourceFragment.kt
Labels: bug

#446 Refactor HiltViewModels ApplicationContext
  app/src/androidTest/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountActivityTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCollectionFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/DeleteCollectionFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/SettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/WebcalFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AccountDetailsFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsActivity.kt
Labels: refactoring
