Repository bitfireAT/davx5-ose, pull requests merged in 2024-10, with the labels that each got.

#1053 Ignore lint AppLinkUrlError
  app/src/main/AndroidManifest.xml
  app/src/ose/AndroidManifest.xml
Labels: bug

#1049 Don't use AccountSettings on main thread
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsScreen.kt
Labels: bug

#1056 Sync worker management: move logic out of companion object
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncAdapterServicesTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/OneTimeSyncWorkerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorkerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/SyncWorkerManagerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/UnifiedPushReceiver.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettingsMigrations.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksAppManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/OneTimeSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/SyncWorkerManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/SyncButtonWidget.kt
Labels: refactoring

#1058 Use SafeAndroidUriHandler to prevent crashes when no browser is installed
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/SyncWorkerManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppTheme.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/UiUtils.kt
Labels: bug

#1050 Add account name to address book account name
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
Labels: bug

#1059 Add KDoc, rename AccountUtils to SystemAccountUtils
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/AccountUtilsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/TestAccountAuthenticator.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Collection.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/account/SystemAccountUtils.kt
Labels: refactoring

#1044 MKCALENDAR: send VTIMEZONE in calendar-timezone
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCalendarModel.kt
  gradle/libs.versions.toml
Labels: bug

#1039 Fix old address book accounts not being deleted
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncAdapterServicesTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/AccountsCleanupWorkerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/App.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettingsMigrations.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/account/AccountsCleanupWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorker.kt
Labels: bug

#1043 [Push] Show notification on push notification (until sync is started)
  app/src/main/kotlin/at/bitfire/davdroid/push/PushNotificationManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/UnifiedPushReceiver.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/SyncWorkerManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/NotificationRegistry.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#1065 Syncer: make sure collections which are deleted are not synced
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/LocalTestCollection.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
Labels: bug

#1069 Fixed surface container color in dark theme
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionsList.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsScreen.kt
  app/src/ose/kotlin/at/bitfire/davdroid/ui/ThemeColors.kt
Labels: bug

#1075 Make collections in CollectionsList clickable again
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionsList.kt
Labels: bug

#1073 Avoid very long log lines and resulting OOM
  app/src/main/kotlin/at/bitfire/davdroid/log/PlainTextFormatter.kt
  app/src/test/kotlin/at/bitfire/davdroid/log/PlainTextFormatterTest.kt
  gradle/libs.versions.toml
Labels: bug

#1081 Don't crash when logging null parameter
  app/src/main/kotlin/at/bitfire/davdroid/log/PlainTextFormatter.kt
  app/src/test/kotlin/at/bitfire/davdroid/log/PlainTextFormatterTest.kt
Labels: bug

#1084 `LocalAddressBook`: move contacts when renaming the address book account
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalTestAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
Labels: bug

#1095 `LocalAddressBook`: rename `account` to `addressbookAccount`
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalTestAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  gradle/libs.versions.toml
Labels: refactoring

#1099 More compatible processing of multiget responses
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
Labels: enhancement

#1094 Replace android sync framework result class with our own
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/TestSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncResult.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
Labels: refactoring
