Repository bitfireAT/davx5-ose, pull requests merged in 2024-08, with the labels that each got.

#907 Generalize syncer
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/LocalTestCollection.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavServiceRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/PrincipalRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskList.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  gradle/libs.versions.toml
Labels: refactoring

#961 [UI] Show push support status in collection details
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#966 Fix sync not running directly after enabling a collection
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
Labels: bug

#971 Don't overwrite calendar/task list color with default color
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskList.kt
Labels: enhancement

#977 SyncAdapterServices: Use a coroutine scope to cancel waiting on framework request
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncAdapterServicesTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
Labels: bug

#984 Log stop reason when sync worker is cancelled
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
Labels: refactoring

#974 Tests for sync algorithm
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
Labels: refactoring

#982 Use standard content provider instead of TaskProvider in TaskSyncer
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTask.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskList.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  gradle/libs.versions.toml
Labels: refactoring
