Repository bitfireAT/davx5-ose, pull requests merged in 2024-05, with the labels that each got.

#754 Rewrite WelcomePage to M3
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/WelcomePage.kt
Labels: refactoring

#769 Switched CalDAV and CardDAV tab positions
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreen.kt
Labels: refactoring

#774 Pre-select per-contact categories for login type NextcloudLogin
  app/src/main/kotlin/at/bitfire/davdroid/network/NextcloudLoginFlow.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginScreenModel.kt
Labels: bug

#772 Start at LoginDetails page if logging in via intent
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginScreenModel.kt
Labels: bug

#767 Replace `DavUtils.lastSegmentOfUrl` by `UrlUtils.lastSegment`
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/syncadapter/TestSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Collection.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/HomeSet.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskList.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/TasksSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/DavUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/UrlUtils.kt
  app/src/test/kotlin/at/bitfire/davdroid/DavUtilsTest.kt
  app/src/test/kotlin/at/bitfire/davdroid/UrlUtilsTest.kt
Labels: refactoring

#776 Use hiltViewModel for creating ViewModels with parameters in new Screen architecture
  app/build.gradle.kts
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateAddressBookActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateAddressBookModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateAddressBookScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCalendarActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCalendarModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCalendarScreen.kt
  gradle/libs.versions.toml
Labels: refactoring

#758 Rewrite PermissionsIntroPage to M3
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/BasicTopAppBar.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/CardWithImage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/PermissionSwitchRow.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/PermissionsIntroPage.kt
Labels: refactoring

#779 Intro pages: use Hilt for dependency injection
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/OpenSourcePage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/PermissionsIntroPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/TasksIntroPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/WelcomePage.kt
  app/src/ose/kotlin/at/bitfire/davdroid/OseFlavorModule.kt
  app/src/ose/kotlin/at/bitfire/davdroid/OseIntroPageFactory.kt
Labels: refactoring

#780 Don't listen for account changes all the time
  app/src/main/kotlin/at/bitfire/davdroid/App.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/ServiceDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavServiceRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/AccountsCleanupWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/AccountsUpdatedListener.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
Labels: refactoring

#760 Rewrite TasksIntroPage to M3
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/TasksIntroPage.kt
Labels: refactoring

#784 Inject SyncDispatcher over Hilt
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/syncadapter/PeriodicSyncWorkerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/OneTimeSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/PeriodicSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/SyncDispatcher.kt
Labels: refactoring

#747 Rewrite BatteryOptimizationsPage to M3
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPageContent.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPageModel.kt
Labels: refactoring

#756 Added M3 theme to intro pages
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/WelcomePage.kt
Labels: refactoring

#744 Rewrite DebugInfoActivity to M3
  app/src/main/kotlin/at/bitfire/davdroid/db/Collection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskList.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/TasksSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoScreen.kt
Labels: enhancement, refactoring

#791 Rewrite WifiPermissionsActivity to M3
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/WifiPermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/WifiPermissionsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/WifiPermissionsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/PermissionSwitchRow.kt
Labels: enhancement, refactoring

#796 M3 tweaks
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsDrawerHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionsList.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/PermissionSwitchRow.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/RadioWithSwitch.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/WelcomePage.kt
Labels: refactoring

#795 Rewrite AccountSettingsActivity to M3
  app/src/main/kotlin/at/bitfire/davdroid/Constants.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsScreen.kt
  app/src/main/res/values/strings.xml
Labels: refactoring

#797 Drop M2 (everything is M3 now)
  app/build.gradle.kts
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppTheme.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/Settings.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/CalendarColorPickerDialog.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/SyncButtonWidget.kt
  app/src/main/res/values/styles.xml
  app/src/ose/kotlin/at/bitfire/davdroid/ui/ThemeColors.kt
  gradle/libs.versions.toml
Labels: refactoring

#799 Fix widget colors
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/SyncButtonWidget.kt
Labels: bug

#782 Fix setup through nextcloud app (intent) not working
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginTypesProvider.kt
  app/src/ose/kotlin/at/bitfire/davdroid/OseFlavorModule.kt
  app/src/ose/kotlin/at/bitfire/davdroid/ui/setup/StandardLoginTypesProvider.kt
Labels: bug

#807 Fix padding for show only personal
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreen.kt
Labels: enhancement

#803 Orange progress indicator bar
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateAddressBookScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCalendarScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/ProgressBar.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AccountDetailsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/DetectResourcesPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/NextcloudLogin.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsScreen.kt
Labels: refactoring

#813 Increased icon size and text size for accounts list
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsScreen.kt
Labels: refactoring

#817 Last M3 Tweaks
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsDrawerHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/PermissionSwitchRow.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsScreen.kt
  app/src/ose/kotlin/at/bitfire/davdroid/ui/ThemeColors.kt
Labels: refactoring

#822 PreferenceRepository.observeAsFlow: emit initial value
  app/src/main/kotlin/at/bitfire/davdroid/repository/PreferenceRepository.kt
Labels: bug

#824 App settings: mention that verbose logs can be viewed in debug info
  app/src/main/res/values/strings.xml
Labels: bug
