Repository bitfireAT/davx5-ose, pull requests merged in 2024-03, with the labels that each got.

#609 Use gradle-managed device for testing
  .github/workflows/test-dev.yml
  app/build.gradle.kts
Labels: refactoring

#617 Rewrite AccountActivity to Compose
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/at/bitfire/davdroid/db/CollectionDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/PrincipalDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/ServiceDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppWarningsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/ExceptionInfoFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AddressBooksFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CalendarsFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionInfoDialog.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionInfoFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionsFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionsList.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateAddressBookActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCalendarActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/DeleteCollectionDialog.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/DeleteCollectionFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/RenameAccountDialog.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/RenameAccountFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/SettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/WebcalFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AccountDetailsFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/ActionCard.kt
  app/src/main/res/layout/account_caldav_item.xml
  app/src/main/res/layout/account_carddav_item.xml
  app/src/main/res/layout/account_collections.xml
  app/src/main/res/layout/delete_collection.xml
  app/src/main/res/menu/account_collection_operations.xml
  app/src/main/res/menu/activity_account.xml
  app/src/main/res/menu/caldav_actions.xml
  app/src/main/res/menu/carddav_actions.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: refactoring

#583 Rewrite `PermissionsActivity`, `PermissionsFragment` to Compose
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsFragment.kt
  app/src/main/res/layout/activity_permissions.xml
  app/src/main/res/values/strings.xml
Labels: refactoring

#626 Rewrite intro pages to Compose (dropping all Fragments)
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroFragmentFactory.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroPageFactory.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/OpenSourcePage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/PermissionsIntroFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/PermissionsIntroPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/TasksIntroFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/TasksIntroPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/WelcomePage.kt
  app/src/main/res/layout/activity_account.xml
  app/src/main/res/layout/intro_permissions.xml
  app/src/ose/kotlin/at/bitfire/davdroid/OseFlavorModule.kt
  app/src/ose/kotlin/at/bitfire/davdroid/OseIntroPageFactory.kt
Labels: refactoring

#630 Rewrite `AddWebdavMountActivity` to Compose
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/PasswordTextField.kt
  app/src/main/res/layout/activity_add_webdav_mount.xml
  app/src/main/res/menu/activity_add_webdav_mount.xml
Labels: refactoring

#628 Rewrite app settings to Compose
  app/build.gradle.kts
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/SettingsManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/ui/AppSettingsActivityTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/at/bitfire/davdroid/App.kt
  app/src/main/kotlin/at/bitfire/davdroid/TasksWatcher.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/Logger.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/TaskUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/SettingsManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/UiUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/InputDialogs.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/Settings.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/PermissionUtils.kt
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en-rGB/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings_app.xml
Labels: refactoring

#632 Improve homepage URL launching
  app/src/main/kotlin/at/bitfire/davdroid/App.kt
  app/src/main/kotlin/at/bitfire/davdroid/Constants.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AboutActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/ExceptionInfoFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/OseAccountsDrawerHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/Theme.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/UiUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateAddressBookActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/SettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/OpenSourcePage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/DetectConfigurationFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/GoogleLoginFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/NextcloudLoginFlowFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsActivity.kt
  app/src/main/res/values/strings.xml
Labels: refactoring

#637 Refactor Tasks app detection (and settings update when tasks apps change)
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/SettingsManagerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/App.kt
  app/src/main/kotlin/at/bitfire/davdroid/PackageChangedReceiver.kt
  app/src/main/kotlin/at/bitfire/davdroid/TasksWatcher.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/TaskUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/Settings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/SettingsManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/SyncUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/OpenSourcePage.kt
Labels: bug

#640 Rewrite WifiPermissionsActivity to Compose
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/at/bitfire/davdroid/Constants.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/WifiPermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/PermissionSwitchRow.kt
  app/src/main/res/layout/activity_wifi_permissions.xml
  app/src/main/res/values/strings.xml
Labels: refactoring

#644 Rewrite navigation drawer to Compose
  app/src/main/kotlin/at/bitfire/davdroid/Constants.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsDrawerHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/BaseAccountsDrawerHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/OseAccountsDrawerHandler.kt
  app/src/main/res/menu/activity_accounts_drawer.xml
  app/src/main/res/values/strings.xml
Labels: refactoring

#652 Better handling of tasks app changes
  app/src/main/kotlin/at/bitfire/davdroid/App.kt
  app/src/main/kotlin/at/bitfire/davdroid/TasksWatcher.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/TaskUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettingsMigrations.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/Settings.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/SyncUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/TasksIntroPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AccountDetailsFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/TaskUtils.kt
Labels: bug

#645 Rewrite CreateCalendarActivity to Compose
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/at/bitfire/davdroid/db/HomeSetDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateAddressBookActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCalendarActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCollectionComposables.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCollectionFragment.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/DeleteCollectionDialog.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/RenameAccountDialog.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/CalendarColorPickerDialog.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/ExceptionInfoDialog.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/InputDialogs.kt
  app/src/main/res/layout/activity_create_calendar.xml
  app/src/main/res/menu/activity_create_collection.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: refactoring

#643 Provide a widget option
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/at/bitfire/davdroid/ui/AboutActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/Theme.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/WifiPermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/ActionCard.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/BindingAdapters.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/Boxes.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/CardWithImage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/CropImageView.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/InputDialogs.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/PasswordTextField.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/PermissionSwitchRow.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/RadioWithSwitch.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/SafeAndroidUriHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/Settings.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/OpenSourcePage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/SyncButtonWidget.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/SyncButtonWidgetReceiver.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/widget_info_sync_button.xml
  gradle/libs.versions.toml
Labels: enhancement

#662 Don't use Gradle build and configuration cache for releases
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-dev.yml
  app/build.gradle.kts
  gradle.properties
Labels: bug

#666 Replaced icons with auto-mirrored version when possible
  app/src/main/kotlin/at/bitfire/davdroid/ui/AboutActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/OseAccountsDrawerHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/WifiPermissionsActivity.kt
Labels: refactoring

#683 OpenSourcePage: make "dontShow" LiveData
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/OpenSourcePage.kt
Labels: bug

#686 SettingsLiveData: post initial value even when it's null
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/SettingsManagerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/SettingsManager.kt
Labels: bug
