Repository bitfireAT/davx5-ose, pull requests merged in 2024-02, with the labels that each got.

#561 Rewrite RenameAccountFragment to compose (closes #478)
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/RenameAccountFragment.kt
  app/src/main/res/values/strings.xml
Labels: refactoring

#559 Rewrite `CreateAddressBookActivity` to Compose
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateAddressBookActivity.kt
  app/src/main/res/layout/activity_create_address_book.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#564 Use gradle version catalog
  app/build.gradle
  build.gradle
  gradle/libs.versions.toml
  settings.gradle
Labels: refactoring

#566 More correct usage of expedited workers
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/syncadapter/SyncWorkerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/PeriodicSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/SyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/SettingsActivity.kt
Labels: refactoring

#580 Rewrite `BatteryOptimizationsFragment` to Compose
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/SettingsManagerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/SettingsManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsFragment.kt
  app/src/main/res/layout/intro_battery_optimizations.xml
Labels: refactoring

#596 Releases: generate release notes and discussion thread automatially
  .github/workflows/release.yml
Labels: enhancement

#582 Rewrite `WelcomeFragment` to Compose
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/WelcomeFragment.kt
  app/src/main/res/layout-land/intro_welcome.xml
  app/src/main/res/layout/intro_welcome.xml
Labels: refactoring

#606 Adapt WelcomeFragment for smaller devices
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/WelcomeFragment.kt
Labels: bug
