Repository bitfireAT/davx5-ose, pull requests merged in 2024-11, with the labels that each got.

#1122 Move dirty verifier logic to ContactDirtyVerifier
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalTestAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalContact.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalGroup.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/workaround/Android7DirtyVerifier.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/workaround/ContactDirtyVerifier.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  gradle/libs.versions.toml
Labels: refactoring

#1123 Set contacts provider settings when address books are renamed or update
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
Labels: bug

#1124 Set or update read-only flag when address books are renamed
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettingsMigrations.kt
Labels: bug

#1131 [Push] Handle subscription expiration
  app/schemas/at.bitfire.davdroid.db.AppDatabase/15.json
  app/src/androidTest/kotlin/at/bitfire/davdroid/TestModules.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/repository/DavCollectionRepositoryTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/AppDatabase.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Collection.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/CollectionDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushRegistrationWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushRegistrationWorkerManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/UnifiedPushReceiver.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#1125 Move local collection management from companion objects to LocalDataStore
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStoreTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalCalendarTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalEventTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/LocalTestCollection.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendarStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalDataStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollectionStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskList.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskListStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettingsMigrations.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/CompatUtils.kt
  gradle.properties
  gradle/libs.versions.toml
Labels: refactoring

#1078 Enforced edge-to-edge
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsDrawerHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppTheme.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/Assistant.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPageContent.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/OpenSourcePage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/PermissionsIntroPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/TasksIntroPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/WelcomePage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsScreen.kt
Labels: enhancement

#1139 Show sync error notification even with big local resource
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
Labels: bug

#1104 Use timezone ID instead of full VTIMEZONE in DB
  app/schemas/at.bitfire.davdroid.db.AppDatabase/16.json
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/AppDatabaseMigrationsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/AppDatabaseTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/CollectionTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/MemoryDbModule.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/AppDatabase.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Collection.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendarStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
Labels: refactoring

#1137 Extract sync framework interaction to separate class
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalTestAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncFrameworkIntegration.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksAppManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
Labels: refactoring

#1142 Don't show app intro again after recomposition
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsScreen.kt
Labels: bug
