Repository bitfireAT/davx5-ose, pull requests merged in 2024-04, with the labels that each got.

#701 Create account: user feedback when account name is already taken
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AccountDetailsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginScreen.kt
Labels: bug

#712 Nextcloud Login Flow: improved handling of back
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginTypeNextcloud.kt
Labels: bug

#716 Detect WebDAV-Push support
  app/schemas/at.bitfire.davdroid.db.AppDatabase/13.json
  app/src/main/kotlin/at/bitfire/davdroid/db/AppDatabase.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Collection.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionInfoDialog.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#714 SettingsManager: use Flows instead of LiveData
  app/build.gradle.kts
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/SettingsManagerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/SettingsManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/OpenSourcePage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AccountDetailsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/TaskUtils.kt
  gradle/libs.versions.toml
Labels: refactoring

#715 Check if keep-permissions changed when user comes back from settings app
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/PermissionsIntroPage.kt
Labels: bug

#722 Use broadcastReceiverFlow instead of BroadcastReceivers
  app/src/main/kotlin/at/bitfire/davdroid/App.kt
  app/src/main/kotlin/at/bitfire/davdroid/PackageChangedReceiver.kt
  app/src/main/kotlin/at/bitfire/davdroid/StorageLowReceiver.kt
  app/src/main/kotlin/at/bitfire/davdroid/TasksAppWatcher.kt
  app/src/main/kotlin/at/bitfire/davdroid/TasksWatcher.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppWarningsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/WifiPermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/BroadcastReceiverFlow.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/TaskUtils.kt
Labels: refactoring

#723 TasksActivity: use defaultValue=true for HINT_OPENTASKS_NOT_INSTALLED
  app/src/main/kotlin/at/bitfire/davdroid/settings/SettingsManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksActivity.kt
Labels: bug

#724 Add non-Compose colorBackground for AppIntro
  app/src/main/res/values/styles.xml
Labels: bug

#725 Use LocalContentColor for ClickableTextWithLink
  app/src/main/kotlin/at/bitfire/davdroid/ui/UiUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/ClickableTextWithLink.kt
Labels: bug

#726 Always use provider.use to automatically close ContentProviderClients
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettingsMigrations.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoActivity.kt
Labels: refactoring

#729 Minor broadcast receiver optimizations
  app/src/main/kotlin/at/bitfire/davdroid/util/BroadcastReceiverFlow.kt
Labels: refactoring

#731 Add M3 theme and apply to AboutActivity
  app/build.gradle.kts
  app/src/main/kotlin/at/bitfire/davdroid/ui/AboutActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppTheme.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateAddressBookActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCalendarActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/WifiPermissionsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/WelcomePage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/SyncButtonWidget.kt
  app/src/ose/kotlin/at/bitfire/davdroid/ui/OpenSourceLicenseInfoProvider.kt
  app/src/ose/kotlin/at/bitfire/davdroid/ui/ThemeColors.kt
  gradle/libs.versions.toml
Labels: refactoring

#743 RefreshCollectionsWorker causes app to crash when the service is invalid
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
Labels: bug

#736 WebDAV Mounts UI: M3, refactoring
  app/build.gradle.kts
  app/src/androidTest/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountActivityTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/WebDavMountRepositoryTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavMountDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavMountWithRootDocument.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/PasswordTextField.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/SelectClientCertificateCard.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/WebDavMountRepository.kt
  gradle/libs.versions.toml
Labels: refactoring

#765 AccountsScreen: move navigation drawer to foreground so that it overlays FABs when open
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsScreen.kt
Labels: bug
