Repository bitfireAT/davx5-ose, pull requests merged in 2024-09, with the labels that each got.

#1001 lint fails in AboutActivity
  app/build.gradle.kts
Labels: bug, 3rd party

#995 Reproducible Builds (for IzzyOnDroid)
  app/build.gradle.kts
  app/src/main/kotlin/at/bitfire/davdroid/network/HttpClient.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AboutActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en-rGB/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-szl/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: refactoring

#986 dark theme / black text basically unreadable on dark background
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroScreen.kt
Labels: enhancement

#1007 InitCalendarProviderRule: make multiple attempts to create a calendar
  app/src/androidTest/kotlin/at/bitfire/davdroid/InitCalendarProviderRule.kt
Labels: bug

#1011 Unsubscribe push from unsynced collections
  app/src/main/kotlin/at/bitfire/davdroid/db/CollectionDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushRegistrationWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
Labels: enhancement

#1017 Update Dependencies
  app/build.gradle.kts
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsScreen.kt
  gradle/libs.versions.toml
Labels: refactoring

#1026 Reword login text
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AccountDetailsPage.kt
  app/src/main/res/values/strings.xml
  app/src/ose/kotlin/at/bitfire/davdroid/ui/setup/StandardLoginTypePage.kt
Labels: refactoring

#1027 Added `isLoading` to `Assistant`
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/Assistant.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AccountDetailsPage.kt
Labels: enhancement

#1024 `ClickableText` for URLs has been deprecated
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/UiUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AdvancedLogin.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/DetectResourcesPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/EmailLogin.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/GoogleLogin.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/UrlLogin.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/ClickableTextWithLink.kt
  app/src/ose/kotlin/at/bitfire/davdroid/ui/OpenSourceLicenseInfoProvider.kt
  app/src/ose/kotlin/at/bitfire/davdroid/ui/setup/StandardLoginTypePage.kt
Labels: refactoring

#1028 Moved pull-to-refresh indicator below tabs
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreen.kt
Labels: enhancement

#989 Remove concept of main accounts
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalGroupTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalTestAddressBook.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/contactrow/CachedGroupMembershipHandlerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/contactrow/GroupMembershipBuilderTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/contactrow/GroupMembershipHandlerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushRegistrationWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettingsMigrations.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksAppManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/account/AccountAuthenticatorService.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/account/AccountsCleanupWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsModel.kt
  gradle/libs.versions.toml
Labels: refactoring
