Repository bitfireAT/davx5-ose, pull requests merged in 2024-07, with the labels that each got.

#868 Show CalDAV/CardDAV tab when the respective service is present
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
Labels: bug

#874 [DI] Use constructor injection for SyncManager sub-classes
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
Labels: refactoring

#883 Replace Apache Commons by native calls/Guava
  app/build.gradle.kts
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresherTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AboutActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPageContent.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/RandomAccessCallback.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/StreamingFileDescriptor.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/cache/DiskCache.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/cache/PageCacheBuilder.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/cache/ThumbnailCache.kt
  app/src/ose/kotlin/at/bitfire/davdroid/ui/OpenSourceLicenseInfoProvider.kt
  app/src/test/kotlin/at/bitfire/davdroid/webdav/DiskCacheTest.kt
  gradle/libs.versions.toml
Labels: refactoring

#889 Use proper DI for Syncer implementations
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
Labels: refactoring

#877 Remove address books sync authority and content provider
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/adapter/AddressBookProvider.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  app/src/main/res/xml/sync_address_books.xml
Labels: refactoring

#881 Provide collection to SyncManager
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/sync/SyncManagerTest.kt
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/sync/TestSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
Labels: refactoring

#906 Refactor logging
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/DavResourceFinderTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/App.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/LogFileHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/LogManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/LogcatHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/Logger.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/LoggerModule.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/PlainTextFormatter.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/StringHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/PreferenceRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/DavResourceFinder.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
  app/src/test/kotlin/at/bitfire/davdroid/log/StringHandlerTest.kt
Labels: refactoring

#901 Get rid of Apache Commons
  app/build.gradle.kts
  app/src/androidTest/kotlin/at/bitfire/davdroid/network/HttpClientTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/TextTable.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Collection.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Principal.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/LogcatHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/PlainTextFormatter.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/MemoryCookieStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/NextcloudLoginFlow.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalGroup.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/contactrow/GroupMembershipHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/DavResourceFinder.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncException.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AdvancedLoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/GoogleLoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/UrlLoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/StringUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/WebDavMountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/cache/DiskCache.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/cache/ThumbnailCache.kt
  app/src/test/kotlin/at/bitfire/davdroid/network/MemoryCookieStoreTest.kt
  app/src/test/kotlin/at/bitfire/davdroid/sync/SyncExceptionTest.kt
  app/src/test/kotlin/at/bitfire/davdroid/util/StringUtilsTest.kt
  gradle/libs.versions.toml
Labels: refactoring

#910 Fix: Syncer synchronizes only once
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
Labels: bug

#911 Use DI for AccountSettings and Android tests
  app/build.gradle.kts
  app/src/androidTest/kotlin/at/bitfire/davdroid/HiltTestRunner.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/InitCalendarProviderRule.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/TestModules.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/CollectionTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/network/ConnectionUtilsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/network/HttpClientTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/repository/DavCollectionRepositoryTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalCalendarTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalEventTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalGroupTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/contactrow/CachedGroupMembershipHandlerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/contactrow/GroupMembershipBuilderTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/contactrow/GroupMembershipHandlerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresherTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/DavResourceFinderTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProviderTest.kt
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/OkhttpClientTest.kt
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/sync/SyncManagerTest.kt
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/sync/TestSyncManager.kt
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/sync/account/AccountUtilsTest.kt
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorkerTest.kt
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/sync/worker/OneTimeSyncWorkerTest.kt
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorkerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushRegistrationWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavSyncStatsRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettingsMigrations.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/OneTimeSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountProgressUseCase.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPageModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/GoogleLoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/NextcloudLoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/TaskUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/WebDavMountRepository.kt
Labels: refactoring

#915 Create interface for startup plugins
  app/src/androidTest/kotlin/at/bitfire/davdroid/TestModules.kt
  app/src/main/kotlin/at/bitfire/davdroid/App.kt
  app/src/main/kotlin/at/bitfire/davdroid/TasksAppWatcher.kt
  app/src/main/kotlin/at/bitfire/davdroid/startup/StartupPlugin.kt
  app/src/main/kotlin/at/bitfire/davdroid/startup/TasksAppWatcher.kt
Labels: bug

#917 Update dnsjava, use desugaring with nio, refactor DNS resolving
  app/build.gradle.kts
  app/src/androidTest/kotlin/at/bitfire/davdroid/network/Android10ResolverTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/network/DnsRecordResolverTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/DavResourceFinderTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/Android10Resolver.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/DnsRecordResolver.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/DavResourceFinder.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/DavUtils.kt
  app/src/test/kotlin/at/bitfire/davdroid/DavUtilsTest.kt
  gradle/libs.versions.toml
Labels: refactoring

#921 WebDAV cache: re-factor using Guava and Hilt
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProviderTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProvider.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/PagingReader.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/RandomAccessCallback.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/RandomAccessCallbackWrapper.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/StreamingFileDescriptor.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/cache/ExtendedLruCache.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/cache/HeadResponseCacheModule.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/cache/PageCacheBuilder.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/cache/ThumbnailCache.kt
  app/src/test/kotlin/at/bitfire/davdroid/webdav/PagingReaderTest.kt
Labels: refactoring

#924 Re-factor Notifications and various Utils to DI
  app/src/androidTest/kotlin/at/bitfire/davdroid/OkhttpClientTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/network/ConnectionUtilsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/LocalTestCollection.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/LocalTestResource.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/TestSyncManager.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/AccountUtilsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/OneTimeSyncWorkerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorkerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/SyncConditionsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/TestSyncWorker.kt
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorkerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/App.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/AppDatabase.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/LogFileHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/LogManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/ConnectionUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncConditions.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/OneTimeSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/NotificationRegistry.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/NotificationUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/PermissionUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/TaskUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/RandomAccessCallback.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/StreamingFileDescriptor.kt
Labels: refactoring

#925 SyncWorker: use Provider for lazy injection
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/TestSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/OneTimeSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorker.kt
Labels: refactoring

#890 DB: some missing indices
  app/schemas/at.bitfire.davdroid.db.AppDatabase/14.json
  app/src/main/kotlin/at/bitfire/davdroid/db/AppDatabase.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Collection.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavDocument.kt
Labels: refactoring

#929 [DI] Use @Inject lateinit var for abstract classes
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/TestSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
Labels: refactoring

#930 Remove obsolete Logger object
  app/src/androidTest/kotlin/at/bitfire/davdroid/InitCalendarProviderRule.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresherTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/DavResourceFinderTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/AppDatabase.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/LogManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/Logger.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/BearerAuthInterceptor.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/GoogleLogin.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/HttpClient.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushMessageParser.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushRegistrationWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/UnifiedPushReceiver.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavSyncStatsRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalContact.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalGroup.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskList.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/contactrow/CachedGroupMembershipHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/contactrow/GroupMembershipHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresher.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettingsMigrations.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncConditions.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/account/AccountUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/account/AccountsCleanupWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/groups/CategoriesStrategy.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/groups/VCard4Strategy.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/OneTimeSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AboutActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/UiUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/SafeAndroidUriHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/GoogleLogin.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/GoogleLoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/NextcloudLoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/BroadcastReceiverFlow.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/PermissionUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/TaskUtils.kt
  app/src/test/kotlin/at/bitfire/davdroid/push/PushMessageParserTest.kt
Labels: refactoring

#928 Debug info: Sync interval "0 min" when actually -1 (manual)
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
Labels: enhancement

#940 Simplify InitCalendarProviderRule
  app/src/androidTest/AndroidManifest.xml
  app/src/androidTest/kotlin/at/bitfire/davdroid/InitCalendarProviderRule.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalCalendarTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalEventTest.kt
Labels: refactoring

#945 WebDAV mounts: fix quota view
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavMountDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavMountWithRootDocument.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/WebdavMountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProvider.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/WebDavMountRepository.kt
Labels: bug

#946 Update ical4android, specify ical4j log level
  .github/release.yml
  app/src/main/assets/logging.properties
  app/src/main/kotlin/at/bitfire/davdroid/log/LogManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTask.kt
  gradle/libs.versions.toml
Labels: dependencies
