Repository bitfireAT/davx5-ose, pull requests merged in 2024-06, with the labels that each got.

#833 [Google] Allow login with custom domains again
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/GoogleLoginModel.kt
Labels: bug

#834 Define toolchain version; update dependencies
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: refactoring

#839 Show CalDAV/CardDAV/Webcal tab when there's at least one item
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
Labels: bug

#845 Extract RefreshCollectionsWorker; move some (HomeSet)Dao calls to repository
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresherTest.kt
  app/src/androidTestOse/kotlin/at/bitfire/davdroid/repository/DavHomeSetRepositoryTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/HomeSetDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavHomeSetRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavServiceRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresher.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/GetBindableHomeSetsFromServiceUseCase.kt
Labels: refactoring

#829 Observable collections repository
  app/src/androidTest/kotlin/at/bitfire/davdroid/repository/DavCollectionRepositoryTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresherTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/CollectionDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresher.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionScreenModel.kt
Labels: refactoring

#800 Add Push Subscription Management
  app/src/androidTest/kotlin/at/bitfire/davdroid/TestModules.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/repository/DavCollectionRepositoryTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresherTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/CollectionDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavServiceRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/syncadapter/PushRegistrationWorker.kt
  gradle/libs.versions.toml
Labels: enhancement

#856 Implement basic Push functionality
  app/build.gradle.kts
  app/src/androidTest/kotlin/at/bitfire/davdroid/TestModules.kt
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/at/bitfire/davdroid/db/CollectionDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/HomeSetDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushMessageParser.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushRegistrationWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/UnifiedPushReceiver.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/PreferenceRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/BasicTopAppBar.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/ExceptionInfoDialog.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/PermissionSwitchRow.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPage.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPageContent.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/BatteryOptimizationsPageModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/PermissionsIntroPage.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/at/bitfire/davdroid/push/PushMessageParserTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#848 Replace AppIntro by Compose Pager
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/WelcomePage.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  gradle/libs.versions.toml
Labels: enhancement

#867 Fix GMD tests
  .github/workflows/codeql.yml
  .github/workflows/test-dev.yml
  run-ci
Labels: bug
