Repository bitfireAT/davx5-ose, pull requests merged in 2024-12, with the labels that each got.

#1146 [Push] Allow UP distributor selection
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsScreen.kt
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1155 Get rid of Head response cache
  app/src/main/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProvider.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/cache/HeadResponseCacheModule.kt
Labels: refactoring, webdav

#1156 AccountSettings: make enable flag for sync intervals explicit
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsScreen.kt
Labels: bug

#1157 Use AutomaticSyncManager to manage periodic workers and sync framework
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AutomaticSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncFrameworkIntegration.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksAppManager.kt
Labels: refactoring

#1151 [Push] Update specification compliance
  app/src/main/kotlin/at/bitfire/davdroid/push/PushMessageParser.kt
  app/src/test/kotlin/at/bitfire/davdroid/push/PushMessageParserTest.kt
  gradle/libs.versions.toml
Labels: refactoring

#1171 Fixed padding problems with Edge-To-Edge
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsDrawerHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginScreen.kt
Labels: bug

#1168 LocalAddressBookStore: return all address books, including orphaned ones
  app/src/androidTest/kotlin/at/bitfire/davdroid/TestModules.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStoreTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalDataStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
Labels: bug

#1181 `AccountSettings`: one class per migration, tests
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/AccountSettingsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration17Test.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncAdapterServicesTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/TestAccountAuthenticator.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettingsMigrations.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration10.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration11.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration12.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration13.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration14.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration15.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration16.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration17.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration7.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration8.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration9.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/account/SystemAccountUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/CompatUtils.kt
Labels: refactoring

#1184 Address book accounts: bind to accounts (again)
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStoreTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalGroupTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalTestAddressBook.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/contactrow/CachedGroupMembershipHandlerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/contactrow/GroupMembershipBuilderTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/contactrow/GroupMembershipHandlerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/AccountSettingsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration17Test.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration18Test.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/AccountsCleanupWorkerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/SystemAccountUtilsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/TestAccountAuthenticator.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendarStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration17.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration18.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/account/AccountsCleanupWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
Labels: bug

#1193 Simplify TasksAppManager and TasksAppWatcher
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/Settings.kt
  app/src/main/kotlin/at/bitfire/davdroid/startup/TasksAppWatcher.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AutomaticSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksAppManager.kt
Labels: refactoring

#1195 `AccountSettings`: allow to create new instances during migrations
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration17Test.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration18Test.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration10.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration11.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration12.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration13.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration14.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration15.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration16.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration17.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration18.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration7.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration8.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration9.kt
Labels: refactoring

#1177 Sync workers: use data type enum instead of specific authority
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/AccountSettingsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration19Test.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/AccountsCleanupWorkerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorkerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/SyncWorkerManagerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushNotificationManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration11.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration14.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration15.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration16.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration19.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AutomaticSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncDataType.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncFrameworkIntegration.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksAppManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/OneTimeSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/SyncWorkerManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/TasksModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountProgressUseCase.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/PermissionUtils.kt
Labels: refactoring

#1202 Trimmed URLs for URI generation
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/UrlLoginModel.kt
Labels: enhancement

#1175 [Push] Upon notification, only enqueue sync for the respective service type
  app/src/main/kotlin/at/bitfire/davdroid/push/UnifiedPushReceiver.kt
Labels: refactoring

#1204 Use bundleOf and contentValuesOf, if applicable
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavDocument.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalContact.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalEvent.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalGroup.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTask.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskList.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/contactrow/GroupMembershipHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration10.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration12.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration8.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/account/AccountAuthenticatorService.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/account/AddressBookAuthenticatorService.kt
Labels: refactoring

#1206 DB: move migrations to separate files and use DI
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/AppDatabaseMigrationsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/AppDatabaseTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/MemoryDbModule.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/migration/AutoMigration16Test.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/migration/DatabaseMigrationTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/TestAccountAuthenticator.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/AppDatabase.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/migration/AutoMigration12.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/migration/AutoMigration16.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/migration/Migration2.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/migration/Migration3.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/migration/Migration4.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/migration/Migration5.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/migration/Migration6.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/migration/Migration7.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/migration/Migration8.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/migration/Migration9.kt
Labels: refactoring
