Repository bitfireAT/davx5-ose, pull requests merged in 2025-08, with the labels that each got.

#1630 WebDAV: remove notifications, timeout logic
  app/build.gradle.kts
  app/src/main/kotlin/at/bitfire/davdroid/ui/NotificationRegistry.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/RandomAccessCallback.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/RandomAccessCallbackWrapper.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/StreamingFileDescriptor.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/CreateDocumentOperation.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/OpenDocumentOperation.kt
  gradle/libs.versions.toml
Labels: refactoring, webdav

#1640 Fix bottom bar color on custom tabs
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/NextcloudLogin.kt
Labels: bug

#1615 Make "sync pending" work in AccountsScreen and AccountScreen
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncDataType.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/adapter/SyncFrameworkIntegration.kt
Labels: bug

#1643 [Sync Framework] Android 14+: Cancel forever pending address book account syncs
  app/src/main/kotlin/at/bitfire/davdroid/sync/adapter/SyncAdapterImpl.kt
Labels: bug

#1650 Change "Account doesn't exist" toast message to "Account has been removed" for deleting accounts
  app/src/main/res/values/strings.xml
Labels: enhancement

#1662 Don't disable sync-ability of address books when set to manual only
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
Labels: bug

#1663 Handle null cases for `Events.DIRTY`
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalCalendarTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCollection.kt
Labels: bug

#1675 Add comments on foreign key constraint enforcement
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/migration/DatabaseMigrationTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/AppDatabase.kt
Labels: documentation
