Repository bitfireAT/davx5-ose, pull requests merged in 2025-02, with the labels that each got.

#1284 Syncer SecurityException: disable permission notification for now
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
Labels: bug

#1290 Update cert4android to avoid Conscrypt crash in custom certificate handling
  gradle/libs.versions.toml
Labels: bug

#1287 Open-source intro page: don't select a "dont show for... months" option by default
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/RadioButtons.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/OpenSourcePage.kt
Labels: bug

#1285 Add migration for Syncer URL → ID change
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration20Test.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration20.kt
Labels: bug

#1299 SyncAdapter: Hilt error handling
  app/src/androidTest/kotlin/at/bitfire/davdroid/HiltTestRunner.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/res/xml/sync_calendars.xml
  app/src/main/res/xml/sync_contacts.xml
  app/src/main/res/xml/sync_notes.xml
  app/src/main/res/xml/sync_opentasks.xml
  app/src/main/res/xml/sync_tasks_org.xml
Labels: bug

#1302 Add syncActive flag to control SyncAdapter behavior during tests
  app/src/androidTest/kotlin/at/bitfire/davdroid/HiltTestRunner.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
Labels: bug

#1304 Refactor: replace deprecated getShowOnlyPersonalPair method and simplify removeAccount logic
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStoreTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
Labels: refactoring

#1267 Skip login type selection when logging in via intent
  app/src/androidTest/kotlin/at/bitfire/davdroid/ui/setup/LoginActivityTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginTypesProvider.kt
  app/src/ose/kotlin/at/bitfire/davdroid/ui/setup/StandardLoginTypesProvider.kt
Labels: bug

#1306 `DnsRecordResolverTest`: Use seeded random number generator for deterministic test result
  app/src/androidTest/kotlin/at/bitfire/davdroid/network/DnsRecordResolverTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/DnsRecordResolver.kt
Labels: bug

#1293 Use `TaskStackBuilder` instead of `PendingIntent.getActivity`
  app/src/main/kotlin/at/bitfire/davdroid/db/AppDatabase.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/LogFileHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushNotificationManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksAppManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/NotificationRegistry.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProvider.kt
Labels: refactoring

#1307 Added confirmation dialog for "Distrust System Certificates"
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#1323 Added timestamp to debug info
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoGenerator.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoScreen.kt
Labels: enhancement
