Repository bitfireAT/davx5-ose, pull requests merged in 2025-05, with the labels that each got.

#1424 [Push] Better title/description for Google FCM in UI
  app/src/main/kotlin/at/bitfire/davdroid/Constants.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsScreen.kt
  app/src/main/res/drawable/product_logomark_cloud_messaging_full_color.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, push

#1444 Send Push-Dont-Notify header
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncManagerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Collection.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  gradle/libs.versions.toml
Labels: enhancement

#1446 Use ical4android that removes ClassLoader checks; refactor SyncDispatcher
  app/src/androidTest/kotlin/at/bitfire/davdroid/di/TestCoroutineDispatchersModule.kt
  app/src/main/kotlin/at/bitfire/davdroid/di/CoroutineDispatchersModule.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalEvent.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncDispatcher.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/OneTimeSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorker.kt
  gradle/libs.versions.toml
Labels: refactoring

#1452 Simplify running suspending tests
  app/src/androidTest/kotlin/at/bitfire/davdroid/HiltTestRunner.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/di/TestCoroutineDispatchersModule.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/di/TestLoggerModule.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/push/UnifiedPushServiceTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/ui/CollectionSelectedUseCaseTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProviderTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/WebDavMountRepositoryTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/di/LoggerModule.kt
Labels: refactoring

#1451 Make SyncManager suspending (first part)
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/TestSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/SyncStatsDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavSyncStatsRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/OneTimeSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorker.kt
Labels: refactoring

#1340 Added widget with just a sync icon
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/IconSyncButtonWidget.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/IconSyncButtonWidgetReceiver.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/LabeledSyncButtonWidget.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/LabeledSyncButtonWidgetReceiver.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/SyncWidgetModel.kt
  app/src/main/res/drawable/shape_rounded_primary.xml
  app/src/main/res/layout/widget_preview_icon_sync_button.xml
  app/src/main/res/layout/widget_preview_labeled_sync_button.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/widget_info_icon_sync_button.xml
  app/src/main/res/xml/widget_info_labeled_sync_button.xml
Labels: enhancement

#1468 Display FCM instead of DAVx⁵ in distributor settings
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsScreen.kt
Labels: bug

#1472 SyncManager: directly wrap HTTP calls with `runInterruptible`
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/TestSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncException.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
Labels: bug, refactoring

#1475 [Sync] Replace `extras` Bundle by explicit arguments
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/JtxSyncManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/TestSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/DavResourceFinder.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ResyncType.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/SyncWorkerManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsModel.kt
Labels: refactoring

#1467 Reset subscription URLs on distributor change
  app/src/main/kotlin/at/bitfire/davdroid/push/PushRegistrationManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsModel.kt
Labels: bug

#1479 [CI] Run tests on pull requests instead of git pushes
  .github/workflows/test-dev.yml
Labels: refactoring

#1480 [Push] Append sync when already syncing
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/SyncWorkerManager.kt
Labels: bug

#1434 Implemented sort order for DAV documents
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/WebDavDocumentDaoTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProviderTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavDocument.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavDocumentDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProvider.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/DocumentSortByMapper.kt
  app/src/test/kotlin/at/bitfire/davdroid/webdav/DocumentSortByMapperTest.kt
Labels: bug

#1481 Handle when AccountActivity is started without account
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginActivity.kt
  app/src/main/res/values/strings.xml
Labels: bug

#1487 TaskSyncer: accept nullable ResyncType
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
Labels: bug

#1483 Credentials / dav4jvm: store passwords as CharArray
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/DavResourceFinderTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/ui/setup/LoginActivityTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/CredentialsStoreTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Credentials.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/HttpClient.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/NextcloudLoginFlow.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/account/SystemAccountUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AdvancedLoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/EmailLoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/UrlLoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/CredentialsStore.kt
  gradle/libs.versions.toml
Labels: refactoring
