Repository bitfireAT/davx5-ose, pull requests merged in 2025-07, with the labels that each got.

#1560 AndroidCalendar refactoring
  app/src/androidTest/kotlin/at/bitfire/davdroid/HiltTestRunner.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/di/TestLoggerModule.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalCalendarTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalEventTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration20Test.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/LogFileHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/LogManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/LogcatHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/PlainTextFormatter.kt
  app/src/main/kotlin/at/bitfire/davdroid/log/StringHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendarStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalDataStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration10.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration20.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration7.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCalendarModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCalendarScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/widget/CalendarColorPickerDialog.kt
  app/src/test/kotlin/at/bitfire/davdroid/log/PlainTextFormatterTest.kt
  gradle/libs.versions.toml
Labels: refactoring

#1569 [Sync framework] Disable contacts content change triggered syncs if sync interval set to manual only
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AutomaticSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncFrameworkIntegration.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountSettingsScreen.kt
Labels: bug

#1572 Synctools: AndroidEvent companion object moved
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalCalendarTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalEventTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendarStore.kt
  gradle/libs.versions.toml
Labels: refactoring

#1573 [synctools] Use `EventReader` / `EventWriter`
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  gradle/libs.versions.toml
Labels: refactoring

#1585 Move SyncState to resource package because it's not in the database
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/LocalTestCollection.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/TestSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Converters.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskList.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/SyncState.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
Labels: refactoring

#1601 Update synctools for `AndroidEvent2`
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalCalendarTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalEventTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/LocalTestResource.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalEvent.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalResource.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration12.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  gradle/libs.versions.toml
Labels: refactoring

#1571 [UI] Use "(optional)" in labels to indicate optional textfields
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateAddressBookScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCalendarScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AdvancedLogin.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/webdav/AddWebdavMountScreen.kt
  app/src/main/res/values/strings.xml
Labels: refactoring

#1463 [Sync framework] Fix sync always pending on Android 14+
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/AndroidSyncFrameworkTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncAdapterServicesTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncFrameworkIntegration.kt
Labels: bug, 3rd party

#1604 Extract `discoverHomesets()` to `ServiceRefresher`
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresherTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/ServiceRefresherTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresher.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/ServiceRefresher.kt
Labels: refactoring

#1608 Choose real or fake (for tests) SyncAdapter over DI
  app/src/androidTest/kotlin/at/bitfire/davdroid/HiltTestRunner.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/di/FakeSyncAdapterModule.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalTestAddressBook.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/FakeSyncAdapter.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncAdapterImplTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AutomaticSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/adapter/SyncAdapter.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/adapter/SyncAdapterImpl.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/adapter/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/adapter/SyncFrameworkIntegration.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoGenerator.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountProgressUseCase.kt
Labels: refactoring

#1610 Use early entry point for sync adapter services
  app/src/main/kotlin/at/bitfire/davdroid/sync/adapter/SyncAdapterServices.kt
Labels: bug

#1617 [WebDAV] Implement command pattern, streamline lifecycle, remove WebdavScope
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/operation/QueryChildDocumentsOperationTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProvider.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/DavHttpClientBuilder.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/DocumentProviderUtils.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/RandomAccessCallbackWrapper.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/WebDavMountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/WebdavScope.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/cache/ThumbnailCache.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/CopyDocumentOperation.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/CreateDocumentOperation.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/DeleteDocumentOperation.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/IsChildDocumentOperation.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/MoveDocumentOperation.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/OpenDocumentOperation.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/OpenDocumentThumbnailOperation.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/QueryChildDocumentsOperation.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/QueryDocumentOperation.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/QueryRootsOperation.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/RenameDocumentOperation.kt
Labels: refactoring

#1625 `AndroidSyncFrameworkTest`: allow optional states
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/AndroidSyncFrameworkTest.kt
Labels: bug

#1622 Correctly handle `SecurityException` for `acquireContentProvider`
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendarStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalDataStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollectionStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskListStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration20.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
Labels: bug

#1626 Fix ETag update logic in QueryChildDocumentsOperation
  app/src/main/kotlin/at/bitfire/davdroid/webdav/operation/QueryChildDocumentsOperation.kt
Labels: bug, webdav
