Repository bitfireAT/davx5-ose, pull requests merged in 2025-01, with the labels that each got.

#1198 Rename account with jtx collection: IllegalArgumentException
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendarStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalDataStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollectionStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskList.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskListStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksAppManager.kt
Labels: bug

#1217 Drop address books authority
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration19Test.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration14.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration19.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AutomaticSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncDataType.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoModel.kt
  app/src/main/res/values/strings.xml
Labels: refactoring

#1224 Remove test account type
  app/src/androidTest/AndroidManifest.xml
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalCalendarTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalEventTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalGroupTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalTestAddressBook.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/contactrow/CachedGroupMembershipHandlerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/contactrow/GroupMembershipBuilderTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/contactrow/GroupMembershipHandlerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/AccountSettingsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration17Test.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncAdapterServicesTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/AccountsCleanupWorkerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/SystemAccountUtilsTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/TestAccount.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/account/TestAccountAuthenticator.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorkerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/SyncWorkerManagerTest.kt
  app/src/androidTest/res/values/strings.xml
  app/src/androidTest/res/xml/test_account_authenticator.xml
  app/src/main/res/xml/sync_calendars.xml
  app/src/main/res/xml/sync_contacts.xml
  app/src/main/res/xml/sync_notes.xml
  app/src/main/res/xml/sync_opentasks.xml
  app/src/main/res/xml/sync_tasks_org.xml
Labels: refactoring

#1227 Use StringDef to annotate possible service and collection types
  app/src/main/kotlin/at/bitfire/davdroid/db/Collection.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Service.kt
Labels: refactoring

#1218 Make room entity properties immutable
  app/src/androidTest/kotlin/at/bitfire/davdroid/repository/DavHomeSetRepositoryTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Collection.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/HomeSet.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Principal.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Service.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/SyncStats.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavDocument.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavDocumentDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavMount.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendarStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollectionStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskListStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresher.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProvider.kt
Labels: refactoring

#1222 Collection list refresh: Don't update fetched homesets
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresherTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Principal.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresher.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
Labels: bug

#1242 Don't remove port from URI of nextcloud login intent
  app/src/androidTest/kotlin/at/bitfire/davdroid/ui/setup/LoginActivityTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginActivity.kt
Labels: bug

#1238 Fix show only personal setting not updating the view immediately
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/GetServiceCollectionPagerUseCase.kt
Labels: bug

#1255 Change warning when Internet is not available
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1252 Use DB StringDefs also in DAOs and methods where they are used
  app/src/main/kotlin/at/bitfire/davdroid/db/CollectionDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/HomeSetDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/ServiceDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavServiceRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/GetServiceCollectionPagerUseCase.kt
Labels: refactoring

#1261 Replaced `LocalContext` casting with `LocalActivity`
  app/src/main/kotlin/at/bitfire/davdroid/ui/composable/SelectClientCertificateCard.kt
Labels: refactoring

#1243 Show a warning if calendar or contacts storage is deactivated or missing
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsScreen.kt
  app/src/main/res/drawable/ic_database_off.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1266 [CI] Use if: !cancelled() instead of if: always()
  .github/workflows/test-dev.yml
Labels: bug

#1250 Use DI for HttpClient.Builder
  app/src/androidTest/kotlin/at/bitfire/davdroid/OkhttpClientTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/db/CollectionTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/network/HttpClientTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/repository/DavCollectionRepositoryTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/repository/DavHomeSetRepositoryTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresherTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/servicedetection/DavResourceFinderTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/TestSyncManager.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProviderTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/ClientCertKeyManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/HttpClient.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/NextcloudLoginFlow.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/OAuthModule.kt
  app/src/main/kotlin/at/bitfire/davdroid/network/UserAgentInterceptor.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushRegistrationWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresher.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/DavResourceFinder.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/ContactsSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TasksSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/NextcloudLoginModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProvider.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/RandomAccessCallbackWrapper.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/WebDavMountRepository.kt
Labels: refactoring

#1269 MockK: use MockkRule if possible
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration18Test.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration19Test.kt
Labels: refactoring

#1251 MKCALENDAR does not send valid calendar-timezone
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
Labels: bug

#1274 Use ID to match DB collections with content provider collections
  app/src/androidTest/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStoreTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration17Test.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/LocalTestCollection.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendar.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendarStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollectionStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskList.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskListStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration17.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoGenerator.kt
  gradle/libs.versions.toml
Labels: refactoring

#1272 Move authority and ContentProvider creation to LocalDataStore
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendarStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalDataStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollectionStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalTaskListStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AddressBookSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/CalendarSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/TaskSyncer.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/worker/BaseSyncWorker.kt
Labels: refactoring
