Repository bitfireAT/davx5-ose, pull requests merged in 2025-04, with the labels that each got.

#1362 Debug Info does not contain actual error
  app/src/main/kotlin/at/bitfire/davdroid/ui/DebugInfoActivity.kt
Labels: bug

#1336 Avoid NPE when missing `DTSTART` for recurring events
  app/src/androidTest/kotlin/at/bitfire/davdroid/CatchExceptionsRule.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/JtxSyncManagerTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollection.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/JtxSyncManager.kt
  gradle/libs.versions.toml
Labels: bug

#1353 Fixed paddings on horizontal mode
  app/src/main/kotlin/at/bitfire/davdroid/ui/AboutActivity.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsDrawerHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AccountsScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppTheme.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/intro/IntroScreen.kt
Labels: bug

#1386 Fix 4.4.9 release compile error
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: bug

#1387 Use ProGuard rules from libraries
  app/proguard-rules-release.pro
  gradle/libs.versions.toml
Labels: refactoring

#1397 Use R8 full mode
  app/build.gradle.kts
  gradle.properties
Labels: refactoring

#1400 Hide "keep permissions" in API 29 and below
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/PermissionsScreen.kt
Labels: bug

#1399 Test coroutines with `runTest` instead of `runBlocking`
  app/build.gradle.kts
  app/src/androidTest/kotlin/at/bitfire/davdroid/repository/DavCollectionRepositoryTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/settings/SettingsManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/SyncAdapterServicesTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/worker/PeriodicSyncWorkerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/WebDavMountRepositoryTest.kt
  gradle/libs.versions.toml
Labels: refactoring

#1401 NPE when trying to log in without specifying an email
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/EmailLogin.kt
Labels: bug

#1383 Sync after sync flag or forceReadOnly flag of a collection are changed
  app/src/main/kotlin/at/bitfire/davdroid/ui/DelayedSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionScreenModel.kt
Labels: enhancement

#1406 Update AboutLibraries to 12.0.0
  app/build.gradle.kts
  app/src/main/kotlin/at/bitfire/davdroid/ui/AboutActivity.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: refactoring

#1405 [WebDAV] Refactor coroutine usage
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProviderTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavDocument.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/WebDavMountDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/CoroutineDispatcherModule.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProvider.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/HeadResponse.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/PagingReader.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/RandomAccessCallback.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/RandomAccessCallbackWrapper.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/StreamingFileDescriptor.kt
  app/src/main/kotlin/at/bitfire/davdroid/webdav/WebDavMountRepository.kt
Labels: refactoring, webdav

#1409 Fix non-suspending DB access on main thread in `accountRepository.delete()`
  app/src/main/kotlin/at/bitfire/davdroid/db/ServiceDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavServiceRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration17.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration20.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/migration/AccountSettingsMigration9.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/AutomaticSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/Syncer.kt
Labels: bug

#1411 [Push] Fix various subscription problems
  app/src/main/kotlin/at/bitfire/davdroid/network/HttpClient.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushRegistrationManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/settings/AccountSettings.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/AppSettingsModel.kt
  gradle/libs.versions.toml
Labels: bug

#1412 [Push] Don't block main thread in UnifiedPushService
  app/src/main/kotlin/at/bitfire/davdroid/push/UnifiedPushService.kt
Labels: refactoring

#1416 Upgrade about libs to 12.1.0
  gradle/libs.versions.toml
Labels: bug, 3rd party

#1407 [Push] Update subscriptions when collection is (un)selected for sync
  app/src/androidTest/kotlin/at/bitfire/davdroid/TestModules.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/repository/DavCollectionRepositoryTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/ui/CollectionSelectedUseCaseTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProviderTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/webdav/WebDavMountRepositoryTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/CollectionDao.kt
  app/src/main/kotlin/at/bitfire/davdroid/db/Service.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/CollectionSelectedUseCase.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/DelayedSyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/AccountScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionScreenModel.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionSelectedUseCase.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/CoroutineDispatcherModule.kt
  app/src/main/kotlin/at/bitfire/davdroid/util/CoroutineScopeModule.kt
Labels: refactoring

#1420 Fix UnifiedPushService tests
  app/src/androidTest/kotlin/at/bitfire/davdroid/push/UnifiedPushServiceTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/UnifiedPushService.kt
Labels: bug

#1421 Clean up app/build.gradle
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: refactoring

#1423 Repositories: apply new naming scheme
  app/src/androidTest/kotlin/at/bitfire/davdroid/repository/DavHomeSetRepositoryTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/sync/JtxSyncManagerTest.kt
  app/src/androidTest/kotlin/at/bitfire/davdroid/ui/CollectionSelectedUseCaseTest.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushMessageHandler.kt
  app/src/main/kotlin/at/bitfire/davdroid/push/PushRegistrationManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/AccountRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavCollectionRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavHomeSetRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavServiceRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/DavSyncStatsRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/repository/PrincipalRepository.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBook.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalAddressBookStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalCalendarStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/resource/LocalJtxCollectionStore.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/CollectionListRefresher.kt
  app/src/main/kotlin/at/bitfire/davdroid/servicedetection/RefreshCollectionsWorker.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncAdapterServices.kt
  app/src/main/kotlin/at/bitfire/davdroid/sync/SyncManager.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/CollectionSelectedUseCase.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CollectionSelectedUseCase.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/LoginScreenModel.kt
Labels: refactoring

#1428 Fixed deprecations with menu anchors
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/CreateCalendarScreen.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/account/HomeSetSelection.kt
  app/src/main/kotlin/at/bitfire/davdroid/ui/setup/AccountDetailsPage.kt
Labels: refactoring
